# Generated by Django 4.1.3 on 2023-11-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='ip',
        ),
    ]
