# Generated by Django 4.2.7 on 2023-11-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_email_comment_subject_comment_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
