# Generated by Django 4.2.7 on 2023-12-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
    ]
