# Generated by Django 4.2.7 on 2023-12-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_replycomment_status_replycomment_update_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomment',
            old_name='comment',
            new_name='repcomment',
        ),
    ]
