# Generated by Django 4.2.7 on 2023-12-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_replycomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
