# Generated by Django 4.2.7 on 2023-12-04 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_comment_replycomment_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycomment',
            name='comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.comment'),
        ),
    ]
