# Generated by Django 4.2.7 on 2023-12-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_replycomment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomment',
            old_name='comment_id',
            new_name='comment',
        ),
    ]
