# Generated by Django 4.2.7 on 2023-12-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_replycomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycomment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.comment'),
        ),
    ]
